wandb_version: 1

architecture:
  desc: null
  value: TinyViT
dataset:
  desc: null
  value: CIFAR-10
lora_rank:
  desc: null
  value: 64
lora_alpha:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 128
num_epochs:
  desc: null
  value: 50
optimizer:
  desc: null
  value: AdamW
scheduler:
  desc: null
  value: CosineAnnealingLR
embed_dim:
  desc: null
  value: 128
num_heads:
  desc: null
  value: 4
num_layers:
  desc: null
  value: 4
patch_size:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1765091340.737343
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
trainable_params:
  desc: null
  value: 419072
total_params:
  desc: null
  value: 948234
trainable_percent:
  desc: null
  value: 44.194998281015025
