wandb_version: 1

embed_dim:
  desc: null
  value: 128
depth:
  desc: null
  value: 6
num_heads:
  desc: null
  value: 4
ranks:
  desc: null
  value:
  - 4
  - 8
  - 16
lora_alphas:
  desc: null
  value:
  - 4
  - 8
  - 16
batch_size:
  desc: null
  value: 128
num_epochs:
  desc: null
  value: 100
learning_rates:
  desc: null
  value:
  - 0.003
  - 0.001
  - 0.0005
update_steps:
  desc: null
  value:
  - 1
  - 2
  - 4
betas:
  desc: null
  value:
  - 0.9
  - 0.999
  - 0.9999
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1765560955.902363
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
