wandb_version: 1

architecture:
  desc: null
  value: TinyViT-MultiRankLoRA-IterationBased
ranks:
  desc: null
  value:
  - 4
  - 8
  - 16
lora_alphas:
  desc: null
  value:
  - 4
  - 8
  - 16
lr_lora1:
  desc: null
  value: 0.03
lr_lora2:
  desc: null
  value: 0.01
lr_lora3:
  desc: null
  value: 0.005
step_lora1:
  desc: null
  value: 1
step_lora2:
  desc: null
  value: 2
step_lora3:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 128
num_epochs:
  desc: null
  value: 100
update_strategy:
  desc: null
  value: iteration_based
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1765498955.383023
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
